services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - .frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true  # 👈 importante para hot-reload en Docker
      - PORT=3000
      - HOST=0.0.0.0              # 👈 React escuchando fuera del contenedor
    restart: always

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    environment:
      - PORT=3001
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=bd_registro_alumnos
    restart: always

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bd_registro_alumnos
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: